name: noahrealstate
version: 2.0.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  intl: ^0.19.0
  flutter_image_slideshow: ^0.1.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  youtube_player_flutter: ^9.0.1
  url_launcher: ^6.2.6
  font_awesome_flutter: ^10.7.0
  flutter_screenutil: ^5.9.1
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.3
  firebase_core: ^3.1.0
  firebase_analytics: ^11.0.1
  flutter_native_splash: ^2.4.0
  mobile_number: ^2.1.1
  permission_handler: ^11.3.1
  contacts_service: ^0.6.3
  simnumber: ^0.0.12
  device_info_plus: ^10.1.0
  device_imei: ^0.0.4+2
 

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
   - family: WorkSans
     fonts:
       - asset: assets/fonts/Montserrat-Regular.ttf
       - asset: assets/fonts/Montserrat-Bold.ttf
         weight: 700
       - asset: assets/fonts/Montserrat-Italic.ttf
         style: italic  

flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: assets/images/noah-launcher.png
  min_sdk_android: 21 # android min sdk min:16, default 21
# flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#ffffff"
  fullscreen: true
  image: assets/images/splash.jpg
 

  android_12:
    image: assets/images/splash.jpg
    

  web: false
 